### ISSUE TITLE
Production checklist

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit-cli#13]
## TODOs
- [x] Test `eth2deposit.deposit` (#14)
- [x] Test `eth2deposit.credentials`
- [x] Windows user instruction
- [x] Better docs
- [x] **important** Go through it aganist the final production version spec again.

@CarlBeek 
I add some backlogs here, feel free to update this issue.
